### PR TITLE
Resolve market participants

### LINKED ISSUE #284: Market participants
We need a way to efficiently get market participants to display on a market card. Ideally we would be able to get this information along with the `market` or `pool`

### PR DESCRIPTION
**Pull request by saboonikhil**
Closes #284

### CODE REVIEW

**Comment by saboonikhil** [comment]
Screenshot 2023-02-08 at 1 40 37 PM

@Robiquet

**Comment by Robiquet** [comment]
Is it possible to query multiple markets at once? Or put a link the markets and stats schemas?

**Comment by saboonikhil** [comment]
How about this?

Screenshot 2023-02-09 at 12 41 50 PM

@Robiquet

**Comment by saboonikhil** [comment]
Renamed `stats` to `marketStats` considering their result from market's perspective

**Pull request merged**
